version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./docker-data/rabbitmq1/data:/var/lib/rabbitmq:rw
      - ./docker-data/rabbitmq1/log:/var/log/rabbitmq:rw
    privileged: true

  rabbitmq2:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./docker-data/rabbitmq2/data:/var/lib/rabbitmq:rw
      - ./docker-data/rabbitmq2/log:/var/log/rabbitmq:rw
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    privileged: true

  rabbitmq3:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./docker-data/rabbitmq3/data:/var/lib/rabbitmq:rw
      - ./docker-data/rabbitmq3/log:/var/log/rabbitmq:rw
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    privileged: true
    
  haproxy:
    image: haproxy:1.7
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
    privileged: true
