version: '3.1'

services:

  rabbitmq1:
    container_name: rabbitmq1
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ${RABBITMQ_DATA_PATH}/rabbitmq1/data:/var/lib/rabbitmq:rw
      - ${RABBITMQ_DATA_PATH}/rabbitmq1/log:/var/log/rabbitmq:rw
    networks:
      - mynet
    privileged: true

  rabbitmq2:
    container_name: rabbitmq2
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ${RABBITMQ_DEFAULT_PATH}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ${RABBITMQ_DATA_PATH}/rabbitmq2/data:/var/lib/rabbitmq:rw
      - ${RABBITMQ_DATA_PATH}/rabbitmq2/log:/var/log/rabbitmq:rw
    networks:
      - mynet
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    privileged: true

  rabbitmq3:
    container_name: rabbitmq3
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ${RABBITMQ_DEFAULT_PATH}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ${RABBITMQ_DATA_PATH}/rabbitmq3/data:/var/lib/rabbitmq:rw
      - ${RABBITMQ_DATA_PATH}/rabbitmq3/log:/var/log/rabbitmq:rw
    networks:
      - mynet
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    privileged: true
    
  haproxy:
    container_name: haproxy
    image: haproxy:1.7
    restart: always
    volumes:
      - ${HAPROXY_DEFAULT_PATH}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - mynet
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    privileged: true

  mw-mariadb:
    container_name: mw-mariadb
    image: mariadb:10.3.9
    restart: always
    hostname: mw-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD} 
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CONFIG_PATH}:/etc/mysql/conf.d
    networks:
      - mynet
    ports:
      - 3306:3306
    privileged: true

  networks:
    mynet:
      external:
        name: ${MW_NETWORK}